-- ============================================================================
-- WinkBench MySQL Migration 0001: Seed Authoritative Taxonomy
-- 22 Main Categories and 189 Subcategories strictly preserved
-- ============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Insert 22 Main Categories
INSERT INTO categories (id, name, slug, icon_name, sort_order, is_active) VALUES
('cat_01_animals_pets', 'Animals & Pets', 'animals-pets', 'Dog', 1, 1),
('cat_02_beauty_wellbeing', 'Beauty & Well-being', 'beauty-wellbeing', 'Sparkles', 2, 1),
('cat_03_events_entertainment', 'Events & Entertainment', 'events-entertainment', 'Ticket', 3, 1),
('cat_04_home_garden', 'Home & Garden', 'home-garden', 'Home', 4, 1),
('cat_05_restaurants_bars', 'Restaurants & Bars', 'restaurants-bars', 'Utensils', 5, 1),
('cat_06_food_beverages_tobacco', 'Food, Beverages & Tobacco', 'food-beverages-tobacco', 'Coffee', 6, 1),
('cat_07_home_services', 'Home Services', 'home-services', 'Wrench', 7, 1),
('cat_08_shopping_fashion', 'Shopping & Fashion', 'shopping-fashion', 'ShoppingBag', 8, 1),
('cat_09_business_services', 'Business Services', 'business-services', 'Briefcase', 9, 1),
('cat_10_legal_services_government', 'Legal Services & Government', 'legal-services-government', 'Scale', 10, 1),
('cat_11_media_publishing', 'Media & Publishing', 'media-publishing', 'BookOpen', 11, 1),
('cat_12_sports', 'Sports', 'sports', 'Trophy', 12, 1),
('cat_13_health_medical', 'Health & Medical', 'health-medical', 'Activity', 13, 1),
('cat_14_construction_manufacturing', 'Construction & Manufacturing', 'construction-manufacturing', 'Building2', 14, 1),
('cat_15_money_insurance', 'Money & Insurance', 'money-insurance', 'CreditCard', 15, 1),
('cat_16_travel_vacation', 'Travel & Vacation', 'travel-vacation', 'Plane', 16, 1),
('cat_17_hobbies_crafts', 'Hobbies & Crafts', 'hobbies-crafts', 'Palette', 17, 1),
('cat_18_education_training', 'Education & Training', 'education-training', 'GraduationCap', 18, 1),
('cat_19_electronics_technology', 'Electronics & Technology', 'electronics-technology', 'Cpu', 19, 1),
('cat_20_public_local_services', 'Public & Local Services', 'public-local-services', 'Users', 20, 1),
('cat_21_utilities', 'Utilities', 'utilities', 'Zap', 21, 1),
('cat_22_vehicles_transportation', 'Vehicles & Transportation', 'vehicles-transportation', 'Car', 22, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  slug = VALUES(slug),
  icon_name = VALUES(icon_name),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);

-- 2. Insert 189 Subcategories
INSERT INTO subcategories (id, category_id, name, slug, sort_order, is_active) VALUES
('sub_01_01', 'cat_01_animals_pets', 'Animal Health', 'animal-health', 1, 1),
('sub_01_02', 'cat_01_animals_pets', 'Animal Parks & Zoo', 'animal-parks-zoo', 2, 1),
('sub_01_03', 'cat_01_animals_pets', 'Cats & Dogs', 'cats-dogs', 3, 1),
('sub_01_04', 'cat_01_animals_pets', 'Horses & Riding', 'horses-riding', 4, 1),
('sub_01_05', 'cat_01_animals_pets', 'Pet Services', 'pet-services', 5, 1),
('sub_01_06', 'cat_01_animals_pets', 'Pet Stores', 'pet-stores', 6, 1),
('sub_02_01', 'cat_02_beauty_wellbeing', 'Cosmetics & Makeup', 'cosmetics-makeup', 1, 1),
('sub_02_02', 'cat_02_beauty_wellbeing', 'Hair Care & Styling', 'hair-care-styling', 2, 1),
('sub_02_03', 'cat_02_beauty_wellbeing', 'Personal Care', 'personal-care', 3, 1),
('sub_02_04', 'cat_02_beauty_wellbeing', 'Salons & Clinics', 'salons-clinics', 4, 1),
('sub_02_05', 'cat_02_beauty_wellbeing', 'Tattoos & Piercings', 'tattoos-piercings', 5, 1),
('sub_02_06', 'cat_02_beauty_wellbeing', 'Wellness & Spa', 'wellness-spa', 6, 1),
('sub_02_07', 'cat_02_beauty_wellbeing', 'Yoga & Meditation', 'yoga-meditation', 7, 1),
('sub_03_01', 'cat_03_events_entertainment', 'Adult Entertainment', 'adult-entertainment', 1, 1),
('sub_03_02', 'cat_03_events_entertainment', 'Children''s Entertainment', 'childrens-entertainment', 2, 1),
('sub_03_03', 'cat_03_events_entertainment', 'Clubbing & Nightlife', 'clubbing-nightlife', 3, 1),
('sub_03_04', 'cat_03_events_entertainment', 'Events & Venues', 'events-venues', 4, 1),
('sub_03_05', 'cat_03_events_entertainment', 'Gambling', 'gambling', 5, 1),
('sub_03_06', 'cat_03_events_entertainment', 'Gaming', 'gaming', 6, 1),
('sub_03_07', 'cat_03_events_entertainment', 'Museums & Exhibits', 'museums-exhibits', 7, 1),
('sub_03_08', 'cat_03_events_entertainment', 'Music & Movies', 'music-movies', 8, 1),
('sub_03_09', 'cat_03_events_entertainment', 'Theater & Opera', 'theater-opera', 9, 1),
('sub_03_10', 'cat_03_events_entertainment', 'Wedding & Party', 'wedding-party', 10, 1),
('sub_04_01', 'cat_04_home_garden', 'Bathroom & Kitchen', 'bathroom-kitchen', 1, 1),
('sub_04_02', 'cat_04_home_garden', 'Cultural Goods', 'cultural-goods', 2, 1),
('sub_04_03', 'cat_04_home_garden', 'Decoration & Interior', 'decoration-interior', 3, 1),
('sub_04_04', 'cat_04_home_garden', 'Energy & Heating', 'energy-heating', 4, 1),
('sub_04_05', 'cat_04_home_garden', 'Fabric & Stationery', 'fabric-stationery', 5, 1),
('sub_04_06', 'cat_04_home_garden', 'Furniture Stores', 'furniture-stores', 6, 1),
('sub_04_07', 'cat_04_home_garden', 'Garden & Pond', 'garden-pond', 7, 1),
('sub_04_08', 'cat_04_home_garden', 'Home & Garden Services', 'home-garden-services', 8, 1),
('sub_04_09', 'cat_04_home_garden', 'Home Goods Stores', 'home-goods-stores', 9, 1),
('sub_04_10', 'cat_04_home_garden', 'Home Improvements', 'home-improvements', 10, 1),
('sub_05_01', 'cat_05_restaurants_bars', 'African & Pacific Cuisine', 'african-pacific-cuisine', 1, 1),
('sub_05_02', 'cat_05_restaurants_bars', 'Bars & Cafes', 'bars-cafes', 2, 1),
('sub_05_03', 'cat_05_restaurants_bars', 'Chinese & Korean Cuisine', 'chinese-korean-cuisine', 3, 1),
('sub_05_04', 'cat_05_restaurants_bars', 'European Cuisine', 'european-cuisine', 4, 1),
('sub_05_05', 'cat_05_restaurants_bars', 'General Restaurants', 'general-restaurants', 5, 1),
('sub_05_06', 'cat_05_restaurants_bars', 'Japanese Cuisine', 'japanese-cuisine', 6, 1),
('sub_05_07', 'cat_05_restaurants_bars', 'Mediterranean Cuisine', 'mediterranean-cuisine', 7, 1),
('sub_05_08', 'cat_05_restaurants_bars', 'Middle Eastern Cuisine', 'middle-eastern-cuisine', 8, 1),
('sub_05_09', 'cat_05_restaurants_bars', 'North & South American Cuisine', 'north-south-american-cuisine', 9, 1),
('sub_05_10', 'cat_05_restaurants_bars', 'Southeast Asian Cuisine', 'southeast-asian-cuisine', 10, 1),
('sub_05_11', 'cat_05_restaurants_bars', 'Takeaway', 'takeaway', 11, 1),
('sub_05_12', 'cat_05_restaurants_bars', 'Vegetarian & Diet', 'vegetarian-diet', 12, 1),
('sub_06_01', 'cat_06_food_beverages_tobacco', 'Agriculture & Produce', 'agriculture-produce', 1, 1),
('sub_06_02', 'cat_06_food_beverages_tobacco', 'Asian Grocery Stores', 'asian-grocery-stores', 2, 1),
('sub_06_03', 'cat_06_food_beverages_tobacco', 'Bakery & Pastry', 'bakery-pastry', 3, 1),
('sub_06_04', 'cat_06_food_beverages_tobacco', 'Beer & Wine', 'beer-wine', 4, 1),
('sub_06_05', 'cat_06_food_beverages_tobacco', 'Beverages & Liquor', 'beverages-liquor', 5, 1),
('sub_06_06', 'cat_06_food_beverages_tobacco', 'Candy & Chocolate', 'candy-chocolate', 6, 1),
('sub_06_07', 'cat_06_food_beverages_tobacco', 'Coffee & Tea', 'coffee-tea', 7, 1),
('sub_06_08', 'cat_06_food_beverages_tobacco', 'Food Production', 'food-production', 8, 1),
('sub_06_09', 'cat_06_food_beverages_tobacco', 'Fruits & Vegetables', 'fruits-vegetables', 9, 1),
('sub_06_10', 'cat_06_food_beverages_tobacco', 'Grocery Stores & Markets', 'grocery-stores-markets', 10, 1),
('sub_06_11', 'cat_06_food_beverages_tobacco', 'Lunch & Catering', 'lunch-catering', 11, 1),
('sub_06_12', 'cat_06_food_beverages_tobacco', 'Meat, Seafood & Eggs', 'meat-seafood-eggs', 12, 1),
('sub_06_13', 'cat_06_food_beverages_tobacco', 'Smoking & Tobacco', 'smoking-tobacco', 13, 1),
('sub_07_01', 'cat_07_home_services', 'Cleaning Service Providers', 'cleaning-service-providers', 1, 1),
('sub_07_02', 'cat_07_home_services', 'Craftsman', 'craftsman', 2, 1),
('sub_07_03', 'cat_07_home_services', 'House Services', 'house-services', 3, 1),
('sub_07_04', 'cat_07_home_services', 'House Sitting & Security', 'house-sitting-security', 4, 1),
('sub_07_05', 'cat_07_home_services', 'Moving & Storage', 'moving-storage', 5, 1),
('sub_07_06', 'cat_07_home_services', 'Plumbing & Sanitation', 'plumbing-sanitation', 6, 1),
('sub_07_07', 'cat_07_home_services', 'Repair Service Providers', 'repair-service-providers', 7, 1),
('sub_08_01', 'cat_08_shopping_fashion', 'Accessories', 'accessories', 1, 1),
('sub_08_02', 'cat_08_shopping_fashion', 'Clothing & Underwear', 'clothing-underwear', 2, 1),
('sub_08_03', 'cat_08_shopping_fashion', 'Clothing Rental & Repair', 'clothing-rental-repair', 3, 1),
('sub_08_04', 'cat_08_shopping_fashion', 'Costume & Wedding', 'costume-wedding', 4, 1),
('sub_08_05', 'cat_08_shopping_fashion', 'Jewelry & Watches', 'jewelry-watches', 5, 1),
('sub_08_06', 'cat_08_shopping_fashion', 'Malls & Marketplaces', 'malls-marketplaces', 6, 1),
('sub_09_01', 'cat_09_business_services', 'Administration & Services', 'administration-services', 1, 1),
('sub_09_02', 'cat_09_business_services', 'Associations & Centers', 'associations-centers', 2, 1),
('sub_09_03', 'cat_09_business_services', 'HR & Recruiting', 'hr-recruiting', 3, 1),
('sub_09_04', 'cat_09_business_services', 'Import & Export', 'import-export', 4, 1),
('sub_09_05', 'cat_09_business_services', 'IT & Communication', 'it-communication', 5, 1),
('sub_09_06', 'cat_09_business_services', 'Office Space & Supplies', 'office-space-supplies', 6, 1),
('sub_09_07', 'cat_09_business_services', 'Print & Graphic Design', 'print-graphic-design', 7, 1),
('sub_09_08', 'cat_09_business_services', 'Research & Development', 'research-development', 8, 1),
('sub_09_09', 'cat_09_business_services', 'Sales & Marketing', 'sales-marketing', 9, 1),
('sub_09_10', 'cat_09_business_services', 'Shipping & Logistics', 'shipping-logistics', 10, 1),
('sub_09_11', 'cat_09_business_services', 'Wholesale', 'wholesale', 11, 1),
('sub_10_01', 'cat_10_legal_services_government', 'Customs & Toll', 'customs-toll', 1, 1),
('sub_10_02', 'cat_10_legal_services_government', 'Government Department', 'government-department', 2, 1),
('sub_10_03', 'cat_10_legal_services_government', 'Law Enforcement', 'law-enforcement', 3, 1),
('sub_10_04', 'cat_10_legal_services_government', 'Lawyers & Attorneys', 'lawyers-attorneys', 4, 1),
('sub_10_05', 'cat_10_legal_services_government', 'Legal Service Providers', 'legal-service-providers', 5, 1),
('sub_10_06', 'cat_10_legal_services_government', 'Libraries & Archives', 'libraries-archives', 6, 1),
('sub_10_07', 'cat_10_legal_services_government', 'Municipal Department', 'municipal-department', 7, 1),
('sub_10_08', 'cat_10_legal_services_government', 'Registration Services', 'registration-services', 8, 1),
('sub_11_01', 'cat_11_media_publishing', 'Books & Magazines', 'books-magazines', 1, 1),
('sub_11_02', 'cat_11_media_publishing', 'Media & Information', 'media-information', 2, 1),
('sub_11_03', 'cat_11_media_publishing', 'Photography', 'photography', 3, 1),
('sub_11_04', 'cat_11_media_publishing', 'Video & Sound', 'video-sound', 4, 1),
('sub_12_01', 'cat_12_sports', 'Ball Games', 'ball-games', 1, 1),
('sub_12_02', 'cat_12_sports', 'Bat-and-ball Games', 'bat-and-ball-games', 2, 1),
('sub_12_03', 'cat_12_sports', 'Bowls & Lawn Sports', 'bowls-lawn-sports', 3, 1),
('sub_12_04', 'cat_12_sports', 'Dancing & Gymnastics', 'dancing-gymnastics', 4, 1),
('sub_12_05', 'cat_12_sports', 'Equipment & Associations', 'equipment-associations', 5, 1),
('sub_12_06', 'cat_12_sports', 'Extreme Sports', 'extreme-sports', 6, 1),
('sub_12_07', 'cat_12_sports', 'Fitness & Weight Lifting', 'fitness-weight-lifting', 7, 1),
('sub_12_08', 'cat_12_sports', 'Golf & Ultimate', 'golf-ultimate', 8, 1),
('sub_12_09', 'cat_12_sports', 'Hockey & Ice Skating', 'hockey-ice-skating', 9, 1),
('sub_12_10', 'cat_12_sports', 'Martial arts & Wrestling', 'martial-arts-wrestling', 10, 1),
('sub_12_11', 'cat_12_sports', 'Outdoor & Winter Sports', 'outdoor-winter-sports', 11, 1),
('sub_12_12', 'cat_12_sports', 'Shooting & Target Sports', 'shooting-target-sports', 12, 1),
('sub_12_13', 'cat_12_sports', 'Swimming & Water Sports', 'swimming-water-sports', 13, 1),
('sub_12_14', 'cat_12_sports', 'Tennis & Racquet Sports', 'tennis-racquet-sports', 14, 1),
('sub_13_01', 'cat_13_health_medical', 'Clinics', 'clinics', 1, 1),
('sub_13_02', 'cat_13_health_medical', 'Dental Services', 'dental-services', 2, 1),
('sub_13_03', 'cat_13_health_medical', 'Diagnostics & Testing', 'diagnostics-testing', 3, 1),
('sub_13_04', 'cat_13_health_medical', 'Doctors & Surgeons', 'doctors-surgeons', 4, 1),
('sub_13_05', 'cat_13_health_medical', 'Health Equipment', 'health-equipment', 5, 1),
('sub_13_06', 'cat_13_health_medical', 'Hospital & Emergency', 'hospital-emergency', 6, 1),
('sub_13_07', 'cat_13_health_medical', 'Medical Specialists', 'medical-specialists', 7, 1),
('sub_13_08', 'cat_13_health_medical', 'Mental Health', 'mental-health', 8, 1),
('sub_13_09', 'cat_13_health_medical', 'Pharmacy & Medicine', 'pharmacy-medicine', 9, 1),
('sub_13_10', 'cat_13_health_medical', 'Physical Aids', 'physical-aids', 10, 1),
('sub_13_11', 'cat_13_health_medical', 'Pregnancy & Children', 'pregnancy-children', 11, 1),
('sub_13_12', 'cat_13_health_medical', 'Therapy & Senior Health', 'therapy-senior-health', 12, 1),
('sub_13_13', 'cat_13_health_medical', 'Vision & Hearing', 'vision-hearing', 13, 1),
('sub_14_01', 'cat_14_construction_manufacturing', 'Architects & Engineers', 'architects-engineers', 1, 1),
('sub_14_02', 'cat_14_construction_manufacturing', 'Building Materials', 'building-materials', 2, 1),
('sub_14_03', 'cat_14_construction_manufacturing', 'Chemicals & Plastic', 'chemicals-plastic', 3, 1),
('sub_14_04', 'cat_14_construction_manufacturing', 'Construction Services', 'construction-services', 4, 1),
('sub_14_05', 'cat_14_construction_manufacturing', 'Contractors & Consultants', 'contractors-consultants', 5, 1),
('sub_14_06', 'cat_14_construction_manufacturing', 'Factory Equipment', 'factory-equipment', 6, 1),
('sub_14_07', 'cat_14_construction_manufacturing', 'Garden & Landscaping', 'garden-landscaping', 7, 1),
('sub_14_08', 'cat_14_construction_manufacturing', 'Industrial Supplies', 'industrial-supplies', 8, 1),
('sub_14_09', 'cat_14_construction_manufacturing', 'Manufacturing', 'manufacturing', 9, 1),
('sub_14_10', 'cat_14_construction_manufacturing', 'Production Services', 'production-services', 10, 1),
('sub_14_11', 'cat_14_construction_manufacturing', 'Tools & Equipment', 'tools-equipment', 11, 1),
('sub_15_01', 'cat_15_money_insurance', 'Accounting & Tax', 'accounting-tax', 1, 1),
('sub_15_02', 'cat_15_money_insurance', 'Banking & Money', 'banking-money', 2, 1),
('sub_15_03', 'cat_15_money_insurance', 'Credit & Debt Services', 'credit-debt-services', 3, 1),
('sub_15_04', 'cat_15_money_insurance', 'Insurance', 'insurance', 4, 1),
('sub_15_05', 'cat_15_money_insurance', 'Investments & Wealth', 'investments-wealth', 5, 1),
('sub_15_06', 'cat_15_money_insurance', 'Real Estate', 'real-estate', 6, 1),
('sub_16_01', 'cat_16_travel_vacation', 'Accommodation & Lodging', 'accommodation-lodging', 1, 1),
('sub_16_02', 'cat_16_travel_vacation', 'Activities & Tours', 'activities-tours', 2, 1),
('sub_16_03', 'cat_16_travel_vacation', 'Airlines & Air Travel', 'airlines-air-travel', 3, 1),
('sub_16_04', 'cat_16_travel_vacation', 'Hotels', 'hotels', 4, 1),
('sub_16_05', 'cat_16_travel_vacation', 'Travel Agencies', 'travel-agencies', 5, 1),
('sub_17_01', 'cat_17_hobbies_crafts', 'Art & Handicraft', 'art-handicraft', 1, 1),
('sub_17_02', 'cat_17_hobbies_crafts', 'Astrology & Numerology', 'astrology-numerology', 2, 1),
('sub_17_03', 'cat_17_hobbies_crafts', 'Fishing & Hunting', 'fishing-hunting', 3, 1),
('sub_17_04', 'cat_17_hobbies_crafts', 'Hobbies', 'hobbies', 4, 1),
('sub_17_05', 'cat_17_hobbies_crafts', 'Metal, Stone & Glass Work', 'metal-stone-glass-work', 5, 1),
('sub_17_06', 'cat_17_hobbies_crafts', 'Music & Instruments', 'music-instruments', 6, 1),
('sub_17_07', 'cat_17_hobbies_crafts', 'Needlework & Knitting', 'needlework-knitting', 7, 1),
('sub_17_08', 'cat_17_hobbies_crafts', 'Outdoor Activities', 'outdoor-activities', 8, 1),
('sub_17_09', 'cat_17_hobbies_crafts', 'Painting & Paper', 'painting-paper', 9, 1),
('sub_18_01', 'cat_18_education_training', 'Colleges & Universities', 'colleges-universities', 1, 1),
('sub_18_02', 'cat_18_education_training', 'Courses & Classes', 'courses-classes', 2, 1),
('sub_18_03', 'cat_18_education_training', 'Education Services', 'education-services', 3, 1),
('sub_18_04', 'cat_18_education_training', 'Language Learning', 'language-learning', 4, 1),
('sub_18_05', 'cat_18_education_training', 'Music & Theater Classes', 'music-theater-classes', 5, 1),
('sub_18_06', 'cat_18_education_training', 'School & High School', 'school-high-school', 6, 1),
('sub_18_07', 'cat_18_education_training', 'Specials Schools', 'specials-schools', 7, 1),
('sub_18_08', 'cat_18_education_training', 'Vocational Training', 'vocational-training', 8, 1),
('sub_19_01', 'cat_19_electronics_technology', 'Appliances & Electronics', 'appliances-electronics', 1, 1),
('sub_19_02', 'cat_19_electronics_technology', 'Audio & Visual', 'audio-visual', 2, 1),
('sub_19_03', 'cat_19_electronics_technology', 'Computers & Phones', 'computers-phones', 3, 1),
('sub_19_04', 'cat_19_electronics_technology', 'Internet & Software', 'internet-software', 4, 1),
('sub_19_05', 'cat_19_electronics_technology', 'Repair & Services', 'repair-services', 5, 1),
('sub_20_01', 'cat_20_public_local_services', 'Employment & Career', 'employment-career', 1, 1),
('sub_20_02', 'cat_20_public_local_services', 'Funeral & Memorial', 'funeral-memorial', 2, 1),
('sub_20_03', 'cat_20_public_local_services', 'Housing Associations', 'housing-associations', 3, 1),
('sub_20_04', 'cat_20_public_local_services', 'Kids & Family', 'kids-family', 4, 1),
('sub_20_05', 'cat_20_public_local_services', 'Military & Veteran', 'military-veteran', 5, 1),
('sub_20_06', 'cat_20_public_local_services', 'Nature & Environment', 'nature-environment', 6, 1),
('sub_20_07', 'cat_20_public_local_services', 'Professional Organizations', 'professional-organizations', 7, 1),
('sub_20_08', 'cat_20_public_local_services', 'Public Services & Welfare', 'public-services-welfare', 8, 1),
('sub_20_09', 'cat_20_public_local_services', 'Religious Institutions', 'religious-institutions', 9, 1),
('sub_20_10', 'cat_20_public_local_services', 'Shelters & Homes', 'shelters-homes', 10, 1),
('sub_20_11', 'cat_20_public_local_services', 'Waste Management', 'waste-management', 11, 1),
('sub_21_01', 'cat_21_utilities', 'Energy & Power', 'energy-power', 1, 1),
('sub_21_02', 'cat_21_utilities', 'Oil & Fuel', 'oil-fuel', 2, 1),
('sub_21_03', 'cat_21_utilities', 'Water Utilities', 'water-utilities', 3, 1),
('sub_22_01', 'cat_22_vehicles_transportation', 'Air & Water Transport', 'air-water-transport', 1, 1),
('sub_22_02', 'cat_22_vehicles_transportation', 'Airports & Parking', 'airports-parking', 2, 1),
('sub_22_03', 'cat_22_vehicles_transportation', 'Auto Parts & Wheels', 'auto-parts-wheels', 3, 1),
('sub_22_04', 'cat_22_vehicles_transportation', 'Bicycles', 'bicycles', 4, 1),
('sub_22_05', 'cat_22_vehicles_transportation', 'Cars & Trucks', 'cars-trucks', 5, 1),
('sub_22_06', 'cat_22_vehicles_transportation', 'Motorcycle & Powersports', 'motorcycle-powersports', 6, 1),
('sub_22_07', 'cat_22_vehicles_transportation', 'Other Vehicles & Trailers', 'other-vehicles-trailers', 7, 1),
('sub_22_08', 'cat_22_vehicles_transportation', 'Taxis & Public Transport', 'taxis-public-transport', 8, 1),
('sub_22_09', 'cat_22_vehicles_transportation', 'Vehicle Rental', 'vehicle-rental', 9, 1),
('sub_22_10', 'cat_22_vehicles_transportation', 'Vehicle Repair & Fuel', 'vehicle-repair-fuel', 10, 1)
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  name = VALUES(name),
  slug = VALUES(slug),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);

SET FOREIGN_KEY_CHECKS = 1;
