import { Company, Category, Review, CommunityPost, CompanyUpdate } from '@/types';

export const DEMO_NOTICE = "DEMO DATA MODE: WinkBench is currently presenting test records in preview mode. Live submissions will connect to Hostinger MySQL upon database configuration.";

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-fin',
    name: 'Financial Services',
    slug: 'financial-services',
    iconName: 'CreditCard',
    description: 'Banks, payment processors, wealth advisors, mortgage brokers, and fintech.',
    companyCount: 1420,
    featured: true,
  },
  {
    id: 'cat-tech',
    name: 'Software & Technology',
    slug: 'software-technology',
    iconName: 'Cpu',
    description: 'Cloud tools, developer platforms, AI products, cybersecurity, and SaaS.',
    companyCount: 2840,
    featured: true,
  },
  {
    id: 'cat-retail',
    name: 'Retail & E-Commerce',
    slug: 'retail-ecommerce',
    iconName: 'ShoppingBag',
    description: 'Direct-to-consumer brands, marketplaces, apparel, electronics, and goods.',
    companyCount: 3910,
    featured: true,
  },
  {
    id: 'cat-health',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    iconName: 'Activity',
    description: 'Clinics, telemedicine, dental services, fitness centers, and nutrition.',
    companyCount: 1720,
    featured: true,
  },
  {
    id: 'cat-travel',
    name: 'Travel & Hospitality',
    slug: 'travel-hospitality',
    iconName: 'Plane',
    description: 'Airlines, hotel booking, travel insurance, tour guides, and car rentals.',
    companyCount: 1250,
    featured: true,
  },
  {
    id: 'cat-home',
    name: 'Home Services & Construction',
    slug: 'home-services',
    iconName: 'Home',
    description: 'Contractors, roofing, plumbing, interior design, and HVAC technicians.',
    companyCount: 2100,
    featured: true,
  },
  {
    id: 'cat-legal',
    name: 'Legal & Business Consulting',
    slug: 'legal-consulting',
    iconName: 'Briefcase',
    description: 'Attorneys, corporate advisory, tax accountants, and patent agents.',
    companyCount: 980,
    featured: false,
  },
  {
    id: 'cat-auto',
    name: 'Automotive & Mobility',
    slug: 'automotive',
    iconName: 'Car',
    description: 'Car dealerships, repair centers, EV charging, and fleet solutions.',
    companyCount: 890,
    featured: false,
  },
];

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'comp-aurora-pay',
    name: 'Aurora Payments Global',
    slug: 'aurora-payments-global',
    tagline: 'Cross-border merchant payouts and global currency settlement',
    description: 'Aurora Payments provides unified multi-currency payment infrastructure for mid-market and enterprise merchants across North America, the UK, and Europe. Offering transparent interchange-plus pricing and PCI-DSS Level 1 compliance.',
    website: 'https://aurorapay.example.com',
    category: 'Financial Services',
    categorySlug: 'financial-services',
    country: 'United Kingdom',
    countryCode: 'GB',
    city: 'London',
    address: '45 Finsbury Square, London EC2A 1PX',
    phone: '+44 20 7946 0912',
    email: 'support@aurorapay.example.com',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.8,
    reviewCount: 384,
    trustScore: 92,
    trustScoreRating: 'High',
    ratingDistribution: { 5: 320, 4: 48, 3: 10, 2: 4, 1: 2 },
    responseRate: 98,
    responseTime: '< 4 hours',
    createdAt: '2023-04-12T10:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'comp-nordic-host',
    name: 'NordicStack Cloud',
    slug: 'nordicstack-cloud',
    tagline: '100% renewable-powered Kubernetes and managed database hosting',
    description: 'NordicStack operates carbon-neutral data facilities across Stockholm, Frankfurt, and Montreal. Engineered for developers who demand sub-millisecond edge latency, NVMe storage tiers, and zero data-mining guarantees.',
    website: 'https://nordicstack.example.io',
    category: 'Software & Technology',
    categorySlug: 'software-technology',
    country: 'Sweden',
    countryCode: 'SE',
    city: 'Stockholm',
    address: 'Sveavägen 82, 113 59 Stockholm',
    phone: '+46 8 123 4567',
    email: 'help@nordicstack.example.io',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.6,
    reviewCount: 512,
    trustScore: 89,
    trustScoreRating: 'Good',
    ratingDistribution: { 5: 380, 4: 90, 3: 22, 2: 12, 1: 8 },
    responseRate: 94,
    responseTime: '< 8 hours',
    createdAt: '2022-11-01T09:00:00Z',
    updatedAt: '2026-09-20T11:00:00Z',
  },
  {
    id: 'comp-pacific-roast',
    name: 'Pacific Heritage Coffee Co.',
    slug: 'pacific-heritage-coffee-co',
    tagline: 'Direct-trade specialty micro-lot beans delivered freshly roasted',
    description: 'Founded in Seattle and operating nationwide across the US and Canada, Pacific Heritage partners directly with generational coffee farms in Guatemala, Ethiopia, and Colombia to roast within 48 hours of dispatch.',
    website: 'https://pacificheritagecoffee.example.com',
    category: 'Retail & E-Commerce',
    categorySlug: 'retail-ecommerce',
    country: 'United States',
    countryCode: 'US',
    city: 'Seattle, WA',
    address: '1420 Western Ave, Seattle, WA 98101',
    phone: '+1 (206) 555-0182',
    email: 'care@pacificheritage.example.com',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.9,
    reviewCount: 1240,
    trustScore: 95,
    trustScoreRating: 'High',
    ratingDistribution: { 5: 1100, 4: 105, 3: 20, 2: 10, 1: 5 },
    responseRate: 99,
    responseTime: '< 2 hours',
    createdAt: '2021-06-15T08:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
  },
  {
    id: 'comp-vanguard-solar',
    name: 'Vanguard Solar & Battery Solutions',
    slug: 'vanguard-solar-battery-solutions',
    tagline: 'Residential solar arrays and microgrid backup installations',
    description: 'Clean energy installation provider operating in Sydney, Melbourne, and Brisbane. Specializing in Tier-1 bifacial photovoltaic panels, lithium-iron-phosphate home storage systems, and government rebate filings.',
    website: 'https://vanguardsolar.example.com.au',
    category: 'Home Services & Construction',
    categorySlug: 'home-services',
    country: 'Australia',
    countryCode: 'AU',
    city: 'Sydney',
    address: '88 George St, The Rocks NSW 2000',
    phone: '+61 2 9876 5432',
    email: 'info@vanguardsolar.example.com.au',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.4,
    reviewCount: 186,
    trustScore: 84,
    trustScoreRating: 'Good',
    ratingDistribution: { 5: 120, 4: 35, 3: 16, 2: 9, 1: 6 },
    responseRate: 88,
    responseTime: '< 24 hours',
    createdAt: '2023-01-20T10:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
  },
  {
    id: 'comp-apex-legal',
    name: 'Apex Global Immigration Law',
    slug: 'apex-global-immigration-law',
    tagline: 'Corporate immigration, work visa sponsorship, and permanent residency',
    description: 'Based in Toronto with partner offices in London and New York. Apex Immigration represents skilled professionals, international founders, and enterprise mobility programs navigating Canadian, UK, and US immigration statutes.',
    website: 'https://apexlegalaustin.example.ca',
    category: 'Legal & Business Consulting',
    categorySlug: 'legal-consulting',
    country: 'Canada',
    countryCode: 'CA',
    city: 'Toronto, ON',
    address: '100 King St W, Suite 3400, Toronto, ON M5X 1A9',
    phone: '+1 (416) 555-7890',
    email: 'consult@apexlegalaustin.example.ca',
    isClaimed: false,
    isVerified: false,
    customerRating: 4.1,
    reviewCount: 94,
    trustScore: 76,
    trustScoreRating: 'Fair',
    ratingDistribution: { 5: 50, 4: 20, 3: 12, 2: 7, 1: 5 },
    responseRate: 60,
    responseTime: '< 48 hours',
    createdAt: '2024-02-10T12:00:00Z',
    updatedAt: '2026-08-30T15:00:00Z',
  },
  {
    id: 'comp-horizon-health',
    name: 'Horizon Virtual Health & Diagnostics',
    slug: 'horizon-virtual-health-diagnostics',
    tagline: '24/7 on-demand board-certified physician consults & home lab kits',
    description: 'Horizon Health combines secure video consultations with clinical-grade at-home capillary blood collection kits. Covering routine general practice, endocrinology, chronic care management, and preventive screenings.',
    website: 'https://horizonhealth.example.com',
    category: 'Health & Wellness',
    categorySlug: 'health-wellness',
    country: 'United States',
    countryCode: 'US',
    city: 'Austin, TX',
    address: '500 W 2nd St, Austin, TX 78701',
    phone: '+1 (512) 555-3419',
    email: 'care@horizonhealth.example.com',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.7,
    reviewCount: 640,
    trustScore: 91,
    trustScoreRating: 'High',
    ratingDistribution: { 5: 510, 4: 90, 3: 24, 2: 10, 1: 6 },
    responseRate: 97,
    responseTime: '< 3 hours',
    createdAt: '2022-08-14T09:00:00Z',
    updatedAt: '2026-09-24T18:00:00Z',
  },
  {
    id: 'comp-zephyr-travel',
    name: 'Zephyr Alpine Expeditions',
    slug: 'zephyr-alpine-expeditions',
    tagline: 'Curated high-altitude trekking and backcountry ski guiding',
    description: 'Certified IFMGA mountain guides delivering small-group expeditions across the European Alps, Rocky Mountains, and Andes. Committed to Leave No Trace principles and mountain safety certification.',
    website: 'https://zephyrexpeditions.example.ch',
    category: 'Travel & Hospitality',
    categorySlug: 'travel-hospitality',
    country: 'Switzerland',
    countryCode: 'CH',
    city: 'Zermatt',
    address: 'Bahnhofstrasse 12, 3920 Zermatt',
    phone: '+41 27 966 8000',
    email: 'bookings@zephyrexpeditions.example.ch',
    isClaimed: true,
    isVerified: true,
    customerRating: 4.95,
    reviewCount: 310,
    trustScore: 96,
    trustScoreRating: 'High',
    ratingDistribution: { 5: 298, 4: 10, 3: 2, 2: 0, 1: 0 },
    responseRate: 99,
    responseTime: '< 2 hours',
    createdAt: '2020-05-18T10:00:00Z',
    updatedAt: '2026-09-27T08:00:00Z',
  },
  {
    id: 'comp-novus-auto',
    name: 'Novus Fleet Electrification',
    slug: 'novus-fleet-electrification',
    tagline: 'Commercial fleet conversion, depot charging hubs, and telematics',
    description: 'Novus equips regional logistics operations and municipal utility fleets with commercial EV vans, smart load-balancing charging depots, and predictive battery degradation diagnostics.',
    website: 'https://novusev.example.co.uk',
    category: 'Automotive & Mobility',
    categorySlug: 'automotive',
    country: 'United Kingdom',
    countryCode: 'GB',
    city: 'Birmingham',
    address: '10 Colmore Row, Birmingham B3 2QD',
    phone: '+44 121 496 0300',
    email: 'fleets@novusev.example.co.uk',
    isClaimed: false,
    isVerified: false,
    customerRating: 3.9,
    reviewCount: 48,
    trustScore: 71,
    trustScoreRating: 'Fair',
    ratingDistribution: { 5: 20, 4: 14, 3: 6, 2: 5, 1: 3 },
    responseRate: 50,
    responseTime: '< 72 hours',
    createdAt: '2024-06-01T11:00:00Z',
    updatedAt: '2026-08-15T12:00:00Z',
  }
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    companyId: 'comp-aurora-pay',
    companyName: 'Aurora Payments Global',
    companySlug: 'aurora-payments-global',
    userId: 'usr-sarah-m',
    userDisplayName: 'Sarah Jenkins',
    userCountry: 'United Kingdom',
    rating: 5,
    title: 'Flawless multi-currency payout processing for our UK eCommerce store',
    content: 'We migrated to Aurora from an older traditional merchant acquirer 9 months ago. Settlement delays dropped from 4 business days to same-day EUR and USD clearing. Their merchant onboarding team assigned a dedicated integration engineer who audited our webhook listeners. Very impressed with the transparent fee schedule.',
    experienceDate: 'September 2026',
    isVerifiedCustomer: true,
    helpfulCount: 24,
    status: 'published',
    reply: {
      id: 'rep-1',
      reviewId: 'rev-1',
      companyId: 'comp-aurora-pay',
      responderName: 'Marcus Vance',
      responderRole: 'Director of Merchant Operations',
      content: 'Thank you Sarah! Ensuring swift multi-currency clearance and dedicated technical support is core to our charter. We are delighted your treasury operations are running smoothly.',
      createdAt: '2026-09-16T10:15:00Z',
    },
    createdAt: '2026-09-15T14:22:00Z',
  },
  {
    id: 'rev-2',
    companyId: 'comp-nordic-host',
    companyName: 'NordicStack Cloud',
    companySlug: 'nordicstack-cloud',
    userId: 'usr-erik-l',
    userDisplayName: 'Erik Lindqvist',
    userCountry: 'Germany',
    rating: 5,
    title: 'Sub-millisecond latency and true green hosting credentials',
    content: 'We host our distributed PostgreSQL replicas across Stockholm and Frankfurt clusters. Uptime has remained 99.995% over the past 14 months. Transparent billing without surprise egress fees. When our primary node had an I/O spike during Black Friday, their automated failover executed without dropped connections.',
    experienceDate: 'August 2026',
    isVerifiedCustomer: true,
    helpfulCount: 18,
    status: 'published',
    reply: {
      id: 'rep-2',
      reviewId: 'rev-2',
      companyId: 'comp-nordic-host',
      responderName: 'Astrid Hedlund',
      responderRole: 'Infrastructure Support Lead',
      content: 'Tack så mycket Erik! Reliable storage failover and sustainable energy usage remain our highest engineering priorities. Happy to have your workloads on NordicStack.',
      createdAt: '2026-08-22T08:40:00Z',
    },
    createdAt: '2026-08-21T18:10:00Z',
  },
  {
    id: 'rev-3',
    companyId: 'comp-pacific-roast',
    companyName: 'Pacific Heritage Coffee Co.',
    companySlug: 'pacific-heritage-coffee-co',
    userId: 'usr-claire-b',
    userDisplayName: 'Claire Beaumont',
    userCountry: 'United States',
    rating: 5,
    title: 'Unbelievably fresh roast dates and transparent direct-trade sourcing',
    content: 'Ordered the Ethiopian Yirgacheffe and Colombian Huila beans. Both roast dates stamped on the valved pouches were only 48 hours prior to arriving on my doorstep in Oregon. The tasting notes (jasmine and bergamot) were spot on. Highly recommended subscription service.',
    experienceDate: 'September 2026',
    isVerifiedCustomer: true,
    helpfulCount: 31,
    status: 'published',
    reply: {
      id: 'rep-3',
      reviewId: 'rev-3',
      companyId: 'comp-pacific-roast',
      responderName: 'Daniel Cole',
      responderRole: 'Head Roaster & Co-Founder',
      content: 'We appreciate the kind words, Claire! Small batch roasting and rapid shipping ensure those delicate florals shine in the cup. Enjoy your morning brews!',
      createdAt: '2026-09-25T11:00:00Z',
    },
    createdAt: '2026-09-24T19:30:00Z',
  },
  {
    id: 'rev-4',
    companyId: 'comp-vanguard-solar',
    companyName: 'Vanguard Solar & Battery Solutions',
    companySlug: 'vanguard-solar-battery-solutions',
    userId: 'usr-liam-k',
    userDisplayName: 'Liam O’Connor',
    userCountry: 'Australia',
    rating: 4,
    title: 'Solid install, clean wiring, small delay with council meter swap',
    content: 'The 10kW panel array and 13.5kWh battery system work as advertised, slashing our quarterly electricity bill by roughly 75%. The installation crew in Sydney was punctual, polite, and cleaned the gutters. The only reason for 4 stars instead of 5 was a 3-week delay waiting for the energy distributor meter reconfiguration.',
    experienceDate: 'July 2026',
    isVerifiedCustomer: true,
    helpfulCount: 12,
    status: 'published',
    reply: {
      id: 'rep-4',
      reviewId: 'rev-4',
      companyId: 'comp-vanguard-solar',
      responderName: 'Chloe Bennett',
      responderRole: 'Customer Operations Manager',
      content: 'G’day Liam, thank you for the honest review. We are delighted with your bill savings! We are actively lobbying distributors to accelerate bi-directional meter sign-offs so future clients avoid that bottleneck.',
      createdAt: '2026-08-01T09:20:00Z',
    },
    createdAt: '2026-07-30T14:45:00Z',
  },
  {
    id: 'rev-5',
    companyId: 'comp-horizon-health',
    companyName: 'Horizon Virtual Health & Diagnostics',
    companySlug: 'horizon-virtual-health-diagnostics',
    userId: 'usr-david-r',
    userDisplayName: 'David Rodriguez',
    userCountry: 'United States',
    rating: 5,
    title: 'Thorough metabolic panel and doctor consultation within 24 hours',
    content: 'The home capillary blood collection kit arrived in an insulated pouch with clear directions. Mailed it back on Tuesday, had my lab results in my patient portal on Thursday, and reviewed the biomarkers with Dr. Martinez over video on Friday morning. Best healthcare experience I’ve had in years.',
    experienceDate: 'September 2026',
    isVerifiedCustomer: true,
    helpfulCount: 19,
    status: 'published',
    createdAt: '2026-09-20T16:15:00Z',
  },
  {
    id: 'rev-6',
    companyId: 'comp-apex-legal',
    companyName: 'Apex Global Immigration Law',
    companySlug: 'apex-global-immigration-law',
    userId: 'usr-amira-t',
    userDisplayName: 'Amira Tariq',
    userCountry: 'Canada',
    rating: 4,
    title: 'Successful work permit approval though initial intake was slow',
    content: 'Once our senior counsel took ownership of the intra-company transfer dossier, the process was handled with exceptional attention to detail. Documents were filed flawlessly with IRCC. Communication was slightly slow during the initial retainment week, but the outcome was 100% successful.',
    experienceDate: 'June 2026',
    isVerifiedCustomer: true,
    helpfulCount: 8,
    status: 'published',
    createdAt: '2026-07-15T11:00:00Z',
  },
];

export const DEMO_UPDATES: CompanyUpdate[] = [
  {
    id: 'upd-1',
    companyId: 'comp-aurora-pay',
    title: 'Expansion into CAD and AUD local banking rails',
    summary: 'Merchants can now initiate local ACH and BECS direct debits without foreign exchange conversion fees.',
    content: 'We are pleased to announce direct domestic clearing rails for Canada (EFT) and Australia (BECS). All Aurora merchants with verified entity registration can activate local currency settlement starting immediately in the merchant portal.',
    publishedAt: '2026-09-10T12:00:00Z',
    authorName: 'Aurora Product Team',
    tag: 'Product Announcement',
  },
  {
    id: 'upd-2',
    companyId: 'comp-nordic-host',
    title: 'Annual ISO/IEC 27001 & SOC 2 Type II recertification completed',
    summary: 'Independent audit confirms zero material findings across data center physical security and encryption key controls.',
    content: 'Our compliance posture has been re-verified by Ernst & Young LLP for the 2025-2026 auditing cycle. Customers may download the attestation package from their security dashboard.',
    publishedAt: '2026-09-01T09:00:00Z',
    authorName: 'NordicStack Compliance Office',
    tag: 'Security & Compliance',
  },
  {
    id: 'upd-3',
    companyId: 'comp-pacific-roast',
    title: 'Winter microlot harvest direct shipment arriving next week',
    summary: 'Exclusive lot from the Finca Santa Rosa cooperative in Antiquia, Colombia.',
    content: 'We partnered with 14 smallholder farmers in Antioquia to secure 80 bags of washed Castillo and Bourbon varieties. Expect notes of candied orange, dark chocolate, and roasted hazelnut.',
    publishedAt: '2026-09-18T15:00:00Z',
    authorName: 'Pacific Heritage Sourcing Team',
    tag: 'Harvest Update',
  }
];

export const DEMO_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'comm-1',
    title: 'How to verify merchant fee disclosures before signing multi-year SaaS contracts',
    content: 'Many B2B buyers get surprised by payment gateway processing tiers and mid-contract rate adjustments. Here is our checklist for negotiating transparent interchange-plus agreements and auditing monthly statements.',
    authorName: 'Rachel Thorne',
    authorCountry: 'United Kingdom',
    category: 'Billing & Contracts',
    likesCount: 54,
    commentsCount: 16,
    createdAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'comm-2',
    title: 'Solar battery payback periods in 2026: Real-world homeowner data across NSW and Victoria',
    content: 'After 2 full years of running our 12kW system with high-frequency time-of-use tariffs, here is the exact financial breakdown including virtual power plant (VPP) feed-in credits.',
    authorName: 'Brett Henderson',
    authorCountry: 'Australia',
    category: 'Home Renewable Energy',
    likesCount: 89,
    commentsCount: 32,
    createdAt: '2026-09-19T08:30:00Z',
  },
  {
    id: 'comm-3',
    title: 'Telemedicine vs. in-person diagnostic clinics: When is virtual care clinically appropriate?',
    content: 'A thoughtful discussion on what conditions are well-served by asynchronous home diagnostics and video care, versus when hands-on examination is medically mandatory.',
    authorName: 'Dr. Gregory Hall',
    authorCountry: 'United States',
    category: 'Consumer Healthcare',
    likesCount: 42,
    commentsCount: 11,
    createdAt: '2026-09-14T17:45:00Z',
  },
];
