/**
 * Authoritative WinkBench Master Taxonomy
 *
 * Source of truth: 22 Main Categories and 189 Subcategories.
 * Exact names, parent-child relationships, and ordering are strictly preserved.
 */

export interface AuthoritativeSubcategory {
  id: string;
  name: string;
  slug: string;
  sortOrder: number;
}

export interface AuthoritativeCategory {
  id: string;
  name: string;
  slug: string;
  sortOrder: number;
  iconName: string;
  subcategories: AuthoritativeSubcategory[];
}

export const AUTHORITATIVE_CATEGORIES: AuthoritativeCategory[] = [
  {
    id: "cat_01_animals_pets",
    name: "Animals & Pets",
    slug: "animals-pets",
    sortOrder: 1,
    iconName: "Dog",
    subcategories: [
      { id: "sub_01_01", name: "Animal Health", slug: "animal-health", sortOrder: 1 },
      { id: "sub_01_02", name: "Animal Parks & Zoo", slug: "animal-parks-zoo", sortOrder: 2 },
      { id: "sub_01_03", name: "Cats & Dogs", slug: "cats-dogs", sortOrder: 3 },
      { id: "sub_01_04", name: "Horses & Riding", slug: "horses-riding", sortOrder: 4 },
      { id: "sub_01_05", name: "Pet Services", slug: "pet-services", sortOrder: 5 },
      { id: "sub_01_06", name: "Pet Stores", slug: "pet-stores", sortOrder: 6 },
    ],
  },
  {
    id: "cat_02_beauty_wellbeing",
    name: "Beauty & Well-being",
    slug: "beauty-wellbeing",
    sortOrder: 2,
    iconName: "Sparkles",
    subcategories: [
      { id: "sub_02_01", name: "Cosmetics & Makeup", slug: "cosmetics-makeup", sortOrder: 1 },
      { id: "sub_02_02", name: "Hair Care & Styling", slug: "hair-care-styling", sortOrder: 2 },
      { id: "sub_02_03", name: "Personal Care", slug: "personal-care", sortOrder: 3 },
      { id: "sub_02_04", name: "Salons & Clinics", slug: "salons-clinics", sortOrder: 4 },
      { id: "sub_02_05", name: "Tattoos & Piercings", slug: "tattoos-piercings", sortOrder: 5 },
      { id: "sub_02_06", name: "Wellness & Spa", slug: "wellness-spa", sortOrder: 6 },
      { id: "sub_02_07", name: "Yoga & Meditation", slug: "yoga-meditation", sortOrder: 7 },
    ],
  },
  {
    id: "cat_03_events_entertainment",
    name: "Events & Entertainment",
    slug: "events-entertainment",
    sortOrder: 3,
    iconName: "Ticket",
    subcategories: [
      { id: "sub_03_01", name: "Adult Entertainment", slug: "adult-entertainment", sortOrder: 1 },
      { id: "sub_03_02", name: "Children's Entertainment", slug: "childrens-entertainment", sortOrder: 2 },
      { id: "sub_03_03", name: "Clubbing & Nightlife", slug: "clubbing-nightlife", sortOrder: 3 },
      { id: "sub_03_04", name: "Events & Venues", slug: "events-venues", sortOrder: 4 },
      { id: "sub_03_05", name: "Gambling", slug: "gambling", sortOrder: 5 },
      { id: "sub_03_06", name: "Gaming", slug: "gaming", sortOrder: 6 },
      { id: "sub_03_07", name: "Museums & Exhibits", slug: "museums-exhibits", sortOrder: 7 },
      { id: "sub_03_08", name: "Music & Movies", slug: "music-movies", sortOrder: 8 },
      { id: "sub_03_09", name: "Theater & Opera", slug: "theater-opera", sortOrder: 9 },
      { id: "sub_03_10", name: "Wedding & Party", slug: "wedding-party", sortOrder: 10 },
    ],
  },
  {
    id: "cat_04_home_garden",
    name: "Home & Garden",
    slug: "home-garden",
    sortOrder: 4,
    iconName: "Home",
    subcategories: [
      { id: "sub_04_01", name: "Bathroom & Kitchen", slug: "bathroom-kitchen", sortOrder: 1 },
      { id: "sub_04_02", name: "Cultural Goods", slug: "cultural-goods", sortOrder: 2 },
      { id: "sub_04_03", name: "Decoration & Interior", slug: "decoration-interior", sortOrder: 3 },
      { id: "sub_04_04", name: "Energy & Heating", slug: "energy-heating", sortOrder: 4 },
      { id: "sub_04_05", name: "Fabric & Stationery", slug: "fabric-stationery", sortOrder: 5 },
      { id: "sub_04_06", name: "Furniture Stores", slug: "furniture-stores", sortOrder: 6 },
      { id: "sub_04_07", name: "Garden & Pond", slug: "garden-pond", sortOrder: 7 },
      { id: "sub_04_08", name: "Home & Garden Services", slug: "home-garden-services", sortOrder: 8 },
      { id: "sub_04_09", name: "Home Goods Stores", slug: "home-goods-stores", sortOrder: 9 },
      { id: "sub_04_10", name: "Home Improvements", slug: "home-improvements", sortOrder: 10 },
    ],
  },
  {
    id: "cat_05_restaurants_bars",
    name: "Restaurants & Bars",
    slug: "restaurants-bars",
    sortOrder: 5,
    iconName: "Utensils",
    subcategories: [
      { id: "sub_05_01", name: "African & Pacific Cuisine", slug: "african-pacific-cuisine", sortOrder: 1 },
      { id: "sub_05_02", name: "Bars & Cafes", slug: "bars-cafes", sortOrder: 2 },
      { id: "sub_05_03", name: "Chinese & Korean Cuisine", slug: "chinese-korean-cuisine", sortOrder: 3 },
      { id: "sub_05_04", name: "European Cuisine", slug: "european-cuisine", sortOrder: 4 },
      { id: "sub_05_05", name: "General Restaurants", slug: "general-restaurants", sortOrder: 5 },
      { id: "sub_05_06", name: "Japanese Cuisine", slug: "japanese-cuisine", sortOrder: 6 },
      { id: "sub_05_07", name: "Mediterranean Cuisine", slug: "mediterranean-cuisine", sortOrder: 7 },
      { id: "sub_05_08", name: "Middle Eastern Cuisine", slug: "middle-eastern-cuisine", sortOrder: 8 },
      { id: "sub_05_09", name: "North & South American Cuisine", slug: "north-south-american-cuisine", sortOrder: 9 },
      { id: "sub_05_10", name: "Southeast Asian Cuisine", slug: "southeast-asian-cuisine", sortOrder: 10 },
      { id: "sub_05_11", name: "Takeaway", slug: "takeaway", sortOrder: 11 },
      { id: "sub_05_12", name: "Vegetarian & Diet", slug: "vegetarian-diet", sortOrder: 12 },
    ],
  },
  {
    id: "cat_06_food_beverages_tobacco",
    name: "Food, Beverages & Tobacco",
    slug: "food-beverages-tobacco",
    sortOrder: 6,
    iconName: "Coffee",
    subcategories: [
      { id: "sub_06_01", name: "Agriculture & Produce", slug: "agriculture-produce", sortOrder: 1 },
      { id: "sub_06_02", name: "Asian Grocery Stores", slug: "asian-grocery-stores", sortOrder: 2 },
      { id: "sub_06_03", name: "Bakery & Pastry", slug: "bakery-pastry", sortOrder: 3 },
      { id: "sub_06_04", name: "Beer & Wine", slug: "beer-wine", sortOrder: 4 },
      { id: "sub_06_05", name: "Beverages & Liquor", slug: "beverages-liquor", sortOrder: 5 },
      { id: "sub_06_06", name: "Candy & Chocolate", slug: "candy-chocolate", sortOrder: 6 },
      { id: "sub_06_07", name: "Coffee & Tea", slug: "coffee-tea", sortOrder: 7 },
      { id: "sub_06_08", name: "Food Production", slug: "food-production", sortOrder: 8 },
      { id: "sub_06_09", name: "Fruits & Vegetables", slug: "fruits-vegetables", sortOrder: 9 },
      { id: "sub_06_10", name: "Grocery Stores & Markets", slug: "grocery-stores-markets", sortOrder: 10 },
      { id: "sub_06_11", name: "Lunch & Catering", slug: "lunch-catering", sortOrder: 11 },
      { id: "sub_06_12", name: "Meat, Seafood & Eggs", slug: "meat-seafood-eggs", sortOrder: 12 },
      { id: "sub_06_13", name: "Smoking & Tobacco", slug: "smoking-tobacco", sortOrder: 13 },
    ],
  },
  {
    id: "cat_07_home_services",
    name: "Home Services",
    slug: "home-services",
    sortOrder: 7,
    iconName: "Wrench",
    subcategories: [
      { id: "sub_07_01", name: "Cleaning Service Providers", slug: "cleaning-service-providers", sortOrder: 1 },
      { id: "sub_07_02", name: "Craftsman", slug: "craftsman", sortOrder: 2 },
      { id: "sub_07_03", name: "House Services", slug: "house-services", sortOrder: 3 },
      { id: "sub_07_04", name: "House Sitting & Security", slug: "house-sitting-security", sortOrder: 4 },
      { id: "sub_07_05", name: "Moving & Storage", slug: "moving-storage", sortOrder: 5 },
      { id: "sub_07_06", name: "Plumbing & Sanitation", slug: "plumbing-sanitation", sortOrder: 6 },
      { id: "sub_07_07", name: "Repair Service Providers", slug: "repair-service-providers", sortOrder: 7 },
    ],
  },
  {
    id: "cat_08_shopping_fashion",
    name: "Shopping & Fashion",
    slug: "shopping-fashion",
    sortOrder: 8,
    iconName: "ShoppingBag",
    subcategories: [
      { id: "sub_08_01", name: "Accessories", slug: "accessories", sortOrder: 1 },
      { id: "sub_08_02", name: "Clothing & Underwear", slug: "clothing-underwear", sortOrder: 2 },
      { id: "sub_08_03", name: "Clothing Rental & Repair", slug: "clothing-rental-repair", sortOrder: 3 },
      { id: "sub_08_04", name: "Costume & Wedding", slug: "costume-wedding", sortOrder: 4 },
      { id: "sub_08_05", name: "Jewelry & Watches", slug: "jewelry-watches", sortOrder: 5 },
      { id: "sub_08_06", name: "Malls & Marketplaces", slug: "malls-marketplaces", sortOrder: 6 },
    ],
  },
  {
    id: "cat_09_business_services",
    name: "Business Services",
    slug: "business-services",
    sortOrder: 9,
    iconName: "Briefcase",
    subcategories: [
      { id: "sub_09_01", name: "Administration & Services", slug: "administration-services", sortOrder: 1 },
      { id: "sub_09_02", name: "Associations & Centers", slug: "associations-centers", sortOrder: 2 },
      { id: "sub_09_03", name: "HR & Recruiting", slug: "hr-recruiting", sortOrder: 3 },
      { id: "sub_09_04", name: "Import & Export", slug: "import-export", sortOrder: 4 },
      { id: "sub_09_05", name: "IT & Communication", slug: "it-communication", sortOrder: 5 },
      { id: "sub_09_06", name: "Office Space & Supplies", slug: "office-space-supplies", sortOrder: 6 },
      { id: "sub_09_07", name: "Print & Graphic Design", slug: "print-graphic-design", sortOrder: 7 },
      { id: "sub_09_08", name: "Research & Development", slug: "research-development", sortOrder: 8 },
      { id: "sub_09_09", name: "Sales & Marketing", slug: "sales-marketing", sortOrder: 9 },
      { id: "sub_09_10", name: "Shipping & Logistics", slug: "shipping-logistics", sortOrder: 10 },
      { id: "sub_09_11", name: "Wholesale", slug: "wholesale", sortOrder: 11 },
    ],
  },
  {
    id: "cat_10_legal_services_government",
    name: "Legal Services & Government",
    slug: "legal-services-government",
    sortOrder: 10,
    iconName: "Scale",
    subcategories: [
      { id: "sub_10_01", name: "Customs & Toll", slug: "customs-toll", sortOrder: 1 },
      { id: "sub_10_02", name: "Government Department", slug: "government-department", sortOrder: 2 },
      { id: "sub_10_03", name: "Law Enforcement", slug: "law-enforcement", sortOrder: 3 },
      { id: "sub_10_04", name: "Lawyers & Attorneys", slug: "lawyers-attorneys", sortOrder: 4 },
      { id: "sub_10_05", name: "Legal Service Providers", slug: "legal-service-providers", sortOrder: 5 },
      { id: "sub_10_06", name: "Libraries & Archives", slug: "libraries-archives", sortOrder: 6 },
      { id: "sub_10_07", name: "Municipal Department", slug: "municipal-department", sortOrder: 7 },
      { id: "sub_10_08", name: "Registration Services", slug: "registration-services", sortOrder: 8 },
    ],
  },
  {
    id: "cat_11_media_publishing",
    name: "Media & Publishing",
    slug: "media-publishing",
    sortOrder: 11,
    iconName: "BookOpen",
    subcategories: [
      { id: "sub_11_01", name: "Books & Magazines", slug: "books-magazines", sortOrder: 1 },
      { id: "sub_11_02", name: "Media & Information", slug: "media-information", sortOrder: 2 },
      { id: "sub_11_03", name: "Photography", slug: "photography", sortOrder: 3 },
      { id: "sub_11_04", name: "Video & Sound", slug: "video-sound", sortOrder: 4 },
    ],
  },
  {
    id: "cat_12_sports",
    name: "Sports",
    slug: "sports",
    sortOrder: 12,
    iconName: "Trophy",
    subcategories: [
      { id: "sub_12_01", name: "Ball Games", slug: "ball-games", sortOrder: 1 },
      { id: "sub_12_02", name: "Bat-and-ball Games", slug: "bat-and-ball-games", sortOrder: 2 },
      { id: "sub_12_03", name: "Bowls & Lawn Sports", slug: "bowls-lawn-sports", sortOrder: 3 },
      { id: "sub_12_04", name: "Dancing & Gymnastics", slug: "dancing-gymnastics", sortOrder: 4 },
      { id: "sub_12_05", name: "Equipment & Associations", slug: "equipment-associations", sortOrder: 5 },
      { id: "sub_12_06", name: "Extreme Sports", slug: "extreme-sports", sortOrder: 6 },
      { id: "sub_12_07", name: "Fitness & Weight Lifting", slug: "fitness-weight-lifting", sortOrder: 7 },
      { id: "sub_12_08", name: "Golf & Ultimate", slug: "golf-ultimate", sortOrder: 8 },
      { id: "sub_12_09", name: "Hockey & Ice Skating", slug: "hockey-ice-skating", sortOrder: 9 },
      { id: "sub_12_10", name: "Martial arts & Wrestling", slug: "martial-arts-wrestling", sortOrder: 10 },
      { id: "sub_12_11", name: "Outdoor & Winter Sports", slug: "outdoor-winter-sports", sortOrder: 11 },
      { id: "sub_12_12", name: "Shooting & Target Sports", slug: "shooting-target-sports", sortOrder: 12 },
      { id: "sub_12_13", name: "Swimming & Water Sports", slug: "swimming-water-sports", sortOrder: 13 },
      { id: "sub_12_14", name: "Tennis & Racquet Sports", slug: "tennis-racquet-sports", sortOrder: 14 },
    ],
  },
  {
    id: "cat_13_health_medical",
    name: "Health & Medical",
    slug: "health-medical",
    sortOrder: 13,
    iconName: "Activity",
    subcategories: [
      { id: "sub_13_01", name: "Clinics", slug: "clinics", sortOrder: 1 },
      { id: "sub_13_02", name: "Dental Services", slug: "dental-services", sortOrder: 2 },
      { id: "sub_13_03", name: "Diagnostics & Testing", slug: "diagnostics-testing", sortOrder: 3 },
      { id: "sub_13_04", name: "Doctors & Surgeons", slug: "doctors-surgeons", sortOrder: 4 },
      { id: "sub_13_05", name: "Health Equipment", slug: "health-equipment", sortOrder: 5 },
      { id: "sub_13_06", name: "Hospital & Emergency", slug: "hospital-emergency", sortOrder: 6 },
      { id: "sub_13_07", name: "Medical Specialists", slug: "medical-specialists", sortOrder: 7 },
      { id: "sub_13_08", name: "Mental Health", slug: "mental-health", sortOrder: 8 },
      { id: "sub_13_09", name: "Pharmacy & Medicine", slug: "pharmacy-medicine", sortOrder: 9 },
      { id: "sub_13_10", name: "Physical Aids", slug: "physical-aids", sortOrder: 10 },
      { id: "sub_13_11", name: "Pregnancy & Children", slug: "pregnancy-children", sortOrder: 11 },
      { id: "sub_13_12", name: "Therapy & Senior Health", slug: "therapy-senior-health", sortOrder: 12 },
      { id: "sub_13_13", name: "Vision & Hearing", slug: "vision-hearing", sortOrder: 13 },
    ],
  },
  {
    id: "cat_14_construction_manufacturing",
    name: "Construction & Manufacturing",
    slug: "construction-manufacturing",
    sortOrder: 14,
    iconName: "Building2",
    subcategories: [
      { id: "sub_14_01", name: "Architects & Engineers", slug: "architects-engineers", sortOrder: 1 },
      { id: "sub_14_02", name: "Building Materials", slug: "building-materials", sortOrder: 2 },
      { id: "sub_14_03", name: "Chemicals & Plastic", slug: "chemicals-plastic", sortOrder: 3 },
      { id: "sub_14_04", name: "Construction Services", slug: "construction-services", sortOrder: 4 },
      { id: "sub_14_05", name: "Contractors & Consultants", slug: "contractors-consultants", sortOrder: 5 },
      { id: "sub_14_06", name: "Factory Equipment", slug: "factory-equipment", sortOrder: 6 },
      { id: "sub_14_07", name: "Garden & Landscaping", slug: "garden-landscaping", sortOrder: 7 },
      { id: "sub_14_08", name: "Industrial Supplies", slug: "industrial-supplies", sortOrder: 8 },
      { id: "sub_14_09", name: "Manufacturing", slug: "manufacturing", sortOrder: 9 },
      { id: "sub_14_10", name: "Production Services", slug: "production-services", sortOrder: 10 },
      { id: "sub_14_11", name: "Tools & Equipment", slug: "tools-equipment", sortOrder: 11 },
    ],
  },
  {
    id: "cat_15_money_insurance",
    name: "Money & Insurance",
    slug: "money-insurance",
    sortOrder: 15,
    iconName: "CreditCard",
    subcategories: [
      { id: "sub_15_01", name: "Accounting & Tax", slug: "accounting-tax", sortOrder: 1 },
      { id: "sub_15_02", name: "Banking & Money", slug: "banking-money", sortOrder: 2 },
      { id: "sub_15_03", name: "Credit & Debt Services", slug: "credit-debt-services", sortOrder: 3 },
      { id: "sub_15_04", name: "Insurance", slug: "insurance", sortOrder: 4 },
      { id: "sub_15_05", name: "Investments & Wealth", slug: "investments-wealth", sortOrder: 5 },
      { id: "sub_15_06", name: "Real Estate", slug: "real-estate", sortOrder: 6 },
    ],
  },
  {
    id: "cat_16_travel_vacation",
    name: "Travel & Vacation",
    slug: "travel-vacation",
    sortOrder: 16,
    iconName: "Plane",
    subcategories: [
      { id: "sub_16_01", name: "Accommodation & Lodging", slug: "accommodation-lodging", sortOrder: 1 },
      { id: "sub_16_02", name: "Activities & Tours", slug: "activities-tours", sortOrder: 2 },
      { id: "sub_16_03", name: "Airlines & Air Travel", slug: "airlines-air-travel", sortOrder: 3 },
      { id: "sub_16_04", name: "Hotels", slug: "hotels", sortOrder: 4 },
      { id: "sub_16_05", name: "Travel Agencies", slug: "travel-agencies", sortOrder: 5 },
    ],
  },
  {
    id: "cat_17_hobbies_crafts",
    name: "Hobbies & Crafts",
    slug: "hobbies-crafts",
    sortOrder: 17,
    iconName: "Palette",
    subcategories: [
      { id: "sub_17_01", name: "Art & Handicraft", slug: "art-handicraft", sortOrder: 1 },
      { id: "sub_17_02", name: "Astrology & Numerology", slug: "astrology-numerology", sortOrder: 2 },
      { id: "sub_17_03", name: "Fishing & Hunting", slug: "fishing-hunting", sortOrder: 3 },
      { id: "sub_17_04", name: "Hobbies", slug: "hobbies", sortOrder: 4 },
      { id: "sub_17_05", name: "Metal, Stone & Glass Work", slug: "metal-stone-glass-work", sortOrder: 5 },
      { id: "sub_17_06", name: "Music & Instruments", slug: "music-instruments", sortOrder: 6 },
      { id: "sub_17_07", name: "Needlework & Knitting", slug: "needlework-knitting", sortOrder: 7 },
      { id: "sub_17_08", name: "Outdoor Activities", slug: "outdoor-activities", sortOrder: 8 },
      { id: "sub_17_09", name: "Painting & Paper", slug: "painting-paper", sortOrder: 9 },
    ],
  },
  {
    id: "cat_18_education_training",
    name: "Education & Training",
    slug: "education-training",
    sortOrder: 18,
    iconName: "GraduationCap",
    subcategories: [
      { id: "sub_18_01", name: "Colleges & Universities", slug: "colleges-universities", sortOrder: 1 },
      { id: "sub_18_02", name: "Courses & Classes", slug: "courses-classes", sortOrder: 2 },
      { id: "sub_18_03", name: "Education Services", slug: "education-services", sortOrder: 3 },
      { id: "sub_18_04", name: "Language Learning", slug: "language-learning", sortOrder: 4 },
      { id: "sub_18_05", name: "Music & Theater Classes", slug: "music-theater-classes", sortOrder: 5 },
      { id: "sub_18_06", name: "School & High School", slug: "school-high-school", sortOrder: 6 },
      { id: "sub_18_07", name: "Specials Schools", slug: "specials-schools", sortOrder: 7 },
      { id: "sub_18_08", name: "Vocational Training", slug: "vocational-training", sortOrder: 8 },
    ],
  },
  {
    id: "cat_19_electronics_technology",
    name: "Electronics & Technology",
    slug: "electronics-technology",
    sortOrder: 19,
    iconName: "Cpu",
    subcategories: [
      { id: "sub_19_01", name: "Appliances & Electronics", slug: "appliances-electronics", sortOrder: 1 },
      { id: "sub_19_02", name: "Audio & Visual", slug: "audio-visual", sortOrder: 2 },
      { id: "sub_19_03", name: "Computers & Phones", slug: "computers-phones", sortOrder: 3 },
      { id: "sub_19_04", name: "Internet & Software", slug: "internet-software", sortOrder: 4 },
      { id: "sub_19_05", name: "Repair & Services", slug: "repair-services", sortOrder: 5 },
    ],
  },
  {
    id: "cat_20_public_local_services",
    name: "Public & Local Services",
    slug: "public-local-services",
    sortOrder: 20,
    iconName: "Users",
    subcategories: [
      { id: "sub_20_01", name: "Employment & Career", slug: "employment-career", sortOrder: 1 },
      { id: "sub_20_02", name: "Funeral & Memorial", slug: "funeral-memorial", sortOrder: 2 },
      { id: "sub_20_03", name: "Housing Associations", slug: "housing-associations", sortOrder: 3 },
      { id: "sub_20_04", name: "Kids & Family", slug: "kids-family", sortOrder: 4 },
      { id: "sub_20_05", name: "Military & Veteran", slug: "military-veteran", sortOrder: 5 },
      { id: "sub_20_06", name: "Nature & Environment", slug: "nature-environment", sortOrder: 6 },
      { id: "sub_20_07", name: "Professional Organizations", slug: "professional-organizations", sortOrder: 7 },
      { id: "sub_20_08", name: "Public Services & Welfare", slug: "public-services-welfare", sortOrder: 8 },
      { id: "sub_20_09", name: "Religious Institutions", slug: "religious-institutions", sortOrder: 9 },
      { id: "sub_20_10", name: "Shelters & Homes", slug: "shelters-homes", sortOrder: 10 },
      { id: "sub_20_11", name: "Waste Management", slug: "waste-management", sortOrder: 11 },
    ],
  },
  {
    id: "cat_21_utilities",
    name: "Utilities",
    slug: "utilities",
    sortOrder: 21,
    iconName: "Zap",
    subcategories: [
      { id: "sub_21_01", name: "Energy & Power", slug: "energy-power", sortOrder: 1 },
      { id: "sub_21_02", name: "Oil & Fuel", slug: "oil-fuel", sortOrder: 2 },
      { id: "sub_21_03", name: "Water Utilities", slug: "water-utilities", sortOrder: 3 },
    ],
  },
  {
    id: "cat_22_vehicles_transportation",
    name: "Vehicles & Transportation",
    slug: "vehicles-transportation",
    sortOrder: 22,
    iconName: "Car",
    subcategories: [
      { id: "sub_22_01", name: "Air & Water Transport", slug: "air-water-transport", sortOrder: 1 },
      { id: "sub_22_02", name: "Airports & Parking", slug: "airports-parking", sortOrder: 2 },
      { id: "sub_22_03", name: "Auto Parts & Wheels", slug: "auto-parts-wheels", sortOrder: 3 },
      { id: "sub_22_04", name: "Bicycles", slug: "bicycles", sortOrder: 4 },
      { id: "sub_22_05", name: "Cars & Trucks", slug: "cars-trucks", sortOrder: 5 },
      { id: "sub_22_06", name: "Motorcycle & Powersports", slug: "motorcycle-powersports", sortOrder: 6 },
      { id: "sub_22_07", name: "Other Vehicles & Trailers", slug: "other-vehicles-trailers", sortOrder: 7 },
      { id: "sub_22_08", name: "Taxis & Public Transport", slug: "taxis-public-transport", sortOrder: 8 },
      { id: "sub_22_09", name: "Vehicle Rental", slug: "vehicle-rental", sortOrder: 9 },
      { id: "sub_22_10", name: "Vehicle Repair & Fuel", slug: "vehicle-repair-fuel", sortOrder: 10 },
    ],
  },
];

export const TOTAL_MAIN_CATEGORIES = AUTHORITATIVE_CATEGORIES.length;

export const TOTAL_SUBCATEGORIES = AUTHORITATIVE_CATEGORIES.reduce(
  (sum, cat) => sum + cat.subcategories.length,
  0
);
